-- DynamicTrading Runtime Rules Data
-- Auto-generated by ModManager on 2026-05-02T09:03:20Z
-- DO NOT hand-edit while ModManager is running.
-- Source: DT/MarketSense/Items/MS_RuntimeRules_Data.lua

return {
    blacklist = { "Animal", "Bag_FoodCanned", "FISH_DEV_ITEM", "Money", "MoneyBundle", "Moveable", "ScratchTicket", "ScratchTicket_Loser", "ScratchTicket_Winner", "TestHotDrink", "TestMug", "TestWaterMug", "Wallet", "Wallet_Female", "Wallet_Male", "YardstickDEBUG" },
    whitelist = {},
    overrides = {
    {
        id = "Base.Battery",
        price = 50,
    }
},
}
