-- Market Sense Tag Taxonomy
-- Flat token taxonomy. Rewritten by refactor to use CamelCase flat tokens.

return {
    generatorVersion = 2,
    schemaVersion = 4,
    signatureVersion = "market-sense-v3-flat-tokens",
    pricingHeuristicVersion = 3,
    categoryOrder = {
        ["Food"]        = 1,
        ["Weapon"]      = 2,
        ["Resource"]    = 3,
        ["Tool"]        = 4,
        ["Container"]   = 5,
        ["Clothing"]    = 6,
        ["Medical"]     = 7,
        ["Electronics"] = 8,
        ["Literature"]  = 9,
        ["Building"]    = 10,
        ["Misc"]        = 11,
        ["Beverage"]    = 12,
    },
    -- Descriptor roots: these prefix dot-notation overlay tags
    descriptorRoots = {
        "Origin",
        "Quality",
        "Rarity",
        "Theme",
    },
    priceTags = {
        -- Root categories
        "Ammo","AmmoBox","AmmoCarton","AmmoMag",
        "Accessory","AccessoryArms","AccessoryFace","AccessoryHead","AccessoryHands","AccessoryJewelry","AccessoryLegs","AccessoryNeck","AccessoryTop",
        "Beverage","BeverageAlcohol","BeverageBeer","BeverageCoffee","BeverageDairy","BeverageJuice","BeverageSoda","BeverageTea","BeverageWater","BeverageWine",
        "BrokenWeapon",
        "Building","BuildingFixture","BuildingFixtureAppliance","BuildingFixturePlumbing","BuildingFurniture","BuildingFurnitureBed","BuildingFurnitureChair","BuildingGarden","BuildingMoveable","BuildingSurvival","BuildingVehicle",
        "ClothingBottom","ClothingFootwear","ClothingFullBody","ClothingHands","ClothingHead","ClothingOuterwear","ClothingSocks","ClothingTop","ClothingUnderwear",
        "Container","ContainerAmmo","ContainerBox","ContainerLiquid","ContainerWearable","ContainerWearableAmmo",
        "Cooking",
        "ElectronicsBattery","ElectronicsCommunicator","ElectronicsGenerator","ElectronicsLight","ElectronicsRadio","ElectronicsTelevision","ElectronicsTransmitter",
        "Electronics",
        "Explosive",
        "FirearmHandgun","FirearmRifle","FirearmShotgun",
        "Firearm",
        "FirstAid","Bandage",
        "FoodNonPerishable","FoodNonPerishableCanned","FoodNonPerishableDish","FoodNonPerishablePortion","FoodNonPerishableSeafood","FoodNonPerishableDairy",
        "FoodPerishable","FoodPerishableCanned","FoodPerishableDish","FoodPerishablePortion","FoodPerishableSeafood","FoodPerishableDairy",
        "FoodPreserved","FoodSpice",
        "Food",
        "Gardening","GardeningCompostable","GardeningSeed","GardeningSeedPacket",
        "KeyRing",
        "LiteratureConsumable","LiteratureFancyBook","LiteratureHardcover","LiteratureMagazine","LiteratureNewspaper","LiteratureOrJunk","LiteraturePhoto","LiteraturePictureBook","LiteratureRecipe","LiteratureSoftcover",
        "Literature","SkillBook",
        "Material","MaterialButchering","MaterialChemical","MaterialFireSource","MaterialHardware","MaterialMaintenance","MaterialMetalworking","MaterialTailoring","MaterialWood",
        "Medical",
        "Memento","MementoPlushie","MementoOrContainer",
        "Misc","Junk",
        "ProtectiveGear",
        "Resource","ResourceFuel",
        "Smoking",
        "Tool","ToolBlacksmith","ToolButchering","ToolCarpentry","ToolCraft","ToolFarming","ToolFlintKnapping","ToolGardening","ToolMaintenance","ToolMasonry","ToolMechanics","ToolPottery","ToolTailoring","ToolWelding",
        "WeaponAxe","WeaponBlunt","WeaponCrafted","WeaponLongBlade","WeaponMelee","WeaponPart","WeaponSpear",
        "Weapon",
        -- Descriptor overlay tags
        "Origin.Vanilla",
        "Quality.Luxury","Quality.Standard","Quality.Sterile","Quality.Waste",
        "Rarity.Common","Rarity.Legendary","Rarity.Rare","Rarity.Uncommon",
        "Theme.Combat","Theme.Industrial","Theme.Militia","Theme.Police","Theme.Primitive","Theme.Survival","Theme.Winter",
    },
}
