-- Market Sense Tag Taxonomy
-- Flat token taxonomy. Rewritten by refactor to use CamelCase flat tokens.

return {
    generatorVersion = 2,
    schemaVersion = 4,
    signatureVersion = "market-sense-v11-root-arbiter-food-pipeline",
    pricingHeuristicVersion = 3,
    categoryOrder = {
        ["Food"]        = 1,
        ["Weapon"]      = 2,
        ["Resource"]    = 3,
        ["Tool"]        = 4,
        ["Container"]   = 5,
        ["Clothing"]    = 6,
        ["Medical"]     = 7,
        ["Electronics"] = 8,
        ["Literature"]  = 9,
        ["Building"]    = 10,
        ["Misc"]        = 11,
    },
    -- Descriptor roots: these prefix dot-notation overlay tags
    descriptorRoots = {
        "Origin",
        "Quality",
        "Rarity",
        "Theme",
    },
    priceTags = {
        -- Root categories
        "Ammo","AmmoBox","AmmoCarton","AmmoMag",
        "Accessory","AccessoryArms","AccessoryFace","AccessoryHead","AccessoryHands","AccessoryJewelry","AccessoryLegs","AccessoryNeck","AccessoryTop",
        "Beverage","BeverageAlcohol","BeverageBeer","BeverageBox","BeverageCoffee","BeverageCocktail","BeverageDairy","BeverageEnergyDrink","BeverageJuice","BeverageMilk","BeverageSoda","BeverageSoftDrink","BeverageTea","BeverageWater","BeverageWine",
        "BrokenWeapon",
        "Building","BuildingFixture","BuildingFixtureAppliance","BuildingFixturePlumbing","BuildingFurniture","BuildingFurnitureBed","BuildingFurnitureChair","BuildingFurnitureCounter","BuildingFurnitureDecor","BuildingFurnitureStorage","BuildingGarden","BuildingMoveable","BuildingSurvival","BuildingSurvivalTrap","BuildingVehicle",
        "ClothingBottom","ClothingFootwear","ClothingFullBody","ClothingHands","ClothingHead","ClothingOuterwear","ClothingSocks","ClothingTop","ClothingUnderwear",
        "Container","ContainerAmmo","ContainerBox","ContainerLiquid","ContainerWearable","ContainerWearableAmmo",
        "Cooking","CookingCup","CookingCutlery","CookingOrTool","CookingPan","CookingUtensil",
        "ElectronicsBattery","ElectronicsCommunicator","ElectronicsGenerator","ElectronicsLight","ElectronicsRadio","ElectronicsTelevision","ElectronicsTransmitter",
        "Electronics",
        "Explosive",
        "FirearmHandgun","FirearmRifle","FirearmShotgun",
        "Firearm",
        "FirstAid","Bandage",
        "FoodBaking","FoodCandy","FoodCheese","FoodCoffee","FoodDish","FoodEgg","FoodFruits","FoodHerb","FoodHotPepper","FoodInsect","FoodLivestock","FoodMeat","FoodMushroom","FoodNoExplicit","FoodNut","FoodPetFood","FoodPortion","FoodSeafood","FoodSeed","FoodSnack","FoodStaple","FoodStock","FoodSugar","FoodTea","FoodVegetables",
        "FoodNonPerishable","FoodNonPerishableBaking","FoodNonPerishableBoxed","FoodNonPerishableBread","FoodNonPerishableCandy","FoodNonPerishableCanned","FoodNonPerishableCheese","FoodNonPerishableDairy","FoodNonPerishableDish","FoodNonPerishableFruits","FoodNonPerishableMeat","FoodNonPerishablePortion","FoodNonPerishableSeafood","FoodNonPerishableSnack","FoodNonPerishableVegetables",
        "FoodPerishable","FoodPerishableBaking","FoodPerishableBread","FoodPerishableCandy","FoodPerishableCheese","FoodPerishableDairy","FoodPerishableDish","FoodPerishableFruits","FoodPerishableMeal","FoodPerishableMeat","FoodPerishablePortion","FoodPerishableSeafood","FoodPerishableSnack","FoodPerishableVegetables",
        "FoodOrFirstAid","FoodPreserved","FoodPreservedPickled","FoodSpice",
        "Food",
        "Gardening","GardeningCompostable","GardeningSeed","GardeningSeedPacket",
        "KeyRing",
        "LiteratureAdult","LiteratureBrochure","LiteratureComic","LiteratureConsumable","LiteratureFancyBook","LiteratureFlier","LiteratureHardcover","LiteratureMagazine","LiteratureNewspaper","LiteratureOrJunk","LiteraturePhoto","LiteraturePictureBook","LiteratureRecipe","LiteratureRpgManual","LiteratureSoftcover",
        "Literature","SkillBook",
        "Material","MaterialBundled","MaterialButchering","MaterialCarpentry","MaterialChemical","MaterialFireSource","MaterialHardware","MaterialMaintenance","MaterialMetalworking","MaterialOrJunk","MaterialPottery","MaterialTailoring","MaterialWood",
        "Medical",
        "Memento","MementoPlushie","MementoOrContainer",
        "Misc","Junk",
        "ProtectiveGear",
        "Resource","ResourceFabric","ResourceFuel","ResourceHardware","ResourceMaterial","ResourceMetal","ResourceParts",
        "Smoking",
        "Tool","ToolBlacksmith","ToolButchering","ToolCarpentry","ToolCraft","ToolFarming","ToolFlintKnapping","ToolGardening","ToolMaintenance","ToolMasonry","ToolMechanics","ToolPottery","ToolTailoring","ToolWelding",
        "WeaponAxe","WeaponBlunt","WeaponCrafted","WeaponExplosive","WeaponLongBlade","WeaponMelee","WeaponPart","WeaponRanged","WeaponSmallBlade","WeaponSmallBlunt","WeaponSpear",
        "Weapon",
        -- Descriptor overlay tags
        "Origin.Vanilla",
        "Quality.Luxury","Quality.Standard","Quality.Sterile","Quality.Waste",
        "Rarity.Common","Rarity.Legendary","Rarity.Rare","Rarity.Uncommon",
        "Theme.Combat","Theme.Industrial","Theme.Militia","Theme.Police","Theme.Primitive","Theme.Survival","Theme.Winter",
    },
}
