"""Read the files emitted into MarketSense's runtime item cache."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .runtime_values import _header_value, _integer, _number, _tags

RUNTIME_INDEX_NAME = "MS_ItemsIndex.txt"

def _runtime_files(root: Path) -> tuple[list[Path], dict[str, Any], list[dict[str, Any]]]:
    """Select the text files that the PZ runtime actually loads.

    ``MS_ItemsIndex.txt`` is the runtime manifest.  Falling back to discovered
    text files keeps the reader useful for older/manual fixtures that predate
    the manifest, while an existing manifest is treated as authoritative.
    """

    discovered = sorted(
        (
            path for path in root.rglob("*.txt")
            if path.relative_to(root).as_posix() != RUNTIME_INDEX_NAME
        ),
        key=lambda path: str(path).casefold(),
    )
    discovered_by_relative = {
        path.relative_to(root).as_posix(): path for path in discovered
    }
    index_path = root / RUNTIME_INDEX_NAME
    metadata: dict[str, Any] = {
        "path": str(index_path),
        "present": index_path.exists(),
        "indexedFileCount": 0,
        "indexedMissingFiles": [],
        "unindexedFileCount": 0,
        "unindexedFiles": [],
    }
    errors: list[dict[str, Any]] = []

    if not index_path.exists():
        return discovered, metadata, errors

    try:
        index_source = index_path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        errors.append({
            "path": RUNTIME_INDEX_NAME,
            "line": 0,
            "kind": "index",
            "message": f"Could not read runtime index: {error}",
        })
        return [], metadata, errors

    indexed_names: list[str] = []
    seen_names: set[str] = set()
    for match in re.finditer(r'path\s*=\s*"([^"\\]*(?:\\.[^"\\]*)*)"', index_source):
        raw_name = match.group(1)
        # Runtime paths are generated as plain slash-separated strings.  Decode
        # the two escapes that can occur without executing the Lua manifest.
        relative_name = raw_name.replace("\\\\", "\\").replace('\\"', '"')
        candidate = (root / relative_name).resolve()
        try:
            candidate.relative_to(root)
        except ValueError:
            errors.append({
                "path": RUNTIME_INDEX_NAME,
                "line": index_source.count("\n", 0, match.start()) + 1,
                "kind": "index",
                "message": f"Runtime index path escapes MS_Items: {relative_name}",
            })
            continue
        normalized_name = candidate.relative_to(root).as_posix()
        if normalized_name in seen_names:
            errors.append({
                "path": RUNTIME_INDEX_NAME,
                "line": index_source.count("\n", 0, match.start()) + 1,
                "kind": "index",
                "message": f"Runtime index lists a file more than once: {normalized_name}",
            })
            continue
        seen_names.add(normalized_name)
        indexed_names.append(normalized_name)

    if not indexed_names:
        errors.append({
            "path": RUNTIME_INDEX_NAME,
            "line": 0,
            "kind": "index",
            "message": "Runtime index contains no readable file entries.",
        })

    selected: list[Path] = []
    missing: list[str] = []
    for relative_name in indexed_names:
        path = discovered_by_relative.get(relative_name)
        if path is None:
            missing.append(relative_name)
            errors.append({
                "path": RUNTIME_INDEX_NAME,
                "line": 0,
                "kind": "index",
                "message": f"Runtime index references missing file: {relative_name}",
            })
            continue
        selected.append(path)

    unindexed = sorted(set(discovered_by_relative) - set(indexed_names))
    metadata["indexedFileCount"] = len(indexed_names)
    metadata["indexedMissingFiles"] = missing
    metadata["unindexedFileCount"] = len(unindexed)
    metadata["unindexedFiles"] = unindexed
    return selected, metadata, errors


def load_runtime_items(runtime_dir: Path) -> tuple[dict[str, dict[str, Any]], dict[str, Any]]:
    """Parse the PZ-generated ``MS_Items/*.txt`` runtime files.

    The parser intentionally reads the grouped text files instead of the Lua
    index. The text files contain the item-level values emitted by MarketSense
    and remain inspectable even when an index was generated by an older
    game/mod version.
    """

    root = runtime_dir.expanduser().resolve()
    if not root.exists():
        raise FileNotFoundError(f"Runtime MS_Items directory does not exist: {root}")
    if not root.is_dir():
        raise NotADirectoryError(f"Runtime MS_Items path is not a directory: {root}")

    files, index_metadata, index_errors = _runtime_files(root)
    items: dict[str, dict[str, Any]] = {}
    errors: list[dict[str, Any]] = list(index_errors)

    for path in files:
        relative_path = str(path.relative_to(root))
        headers: dict[str, str] = {}
        origin = "Vanilla"
        group_tags: list[str] = []
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeError) as error:
            errors.append({
                "path": relative_path,
                "line": 0,
                "kind": "read",
                "message": str(error),
            })
            continue

        for line_number, raw_line in enumerate(lines, start=1):
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("#"):
                declaration = line[1:].strip()
                if "=" in declaration:
                    key, value = declaration.split("=", 1)
                    headers[key.strip()] = value.strip()
                continue
            if line.startswith("@"):
                declaration = line[1:]
                if "=" in declaration:
                    key, value = declaration.split("=", 1)
                    key = key.strip()
                    if key == "origin":
                        origin = value.strip() or "Vanilla"
                    elif key == "tags":
                        group_tags = _tags(value)
                continue

            fields = [field.strip() for field in line.split("|")]
            if len(fields) < 4 or not fields[0]:
                errors.append({
                    "path": relative_path,
                    "line": line_number,
                    "kind": "row",
                    "message": "Expected fullType|basePrice|stockMin|stockMax.",
                })
                continue

            full_type = fields[0]
            base_price = _number(fields[1])
            stock_min = _integer(fields[2])
            stock_max = _integer(fields[3])
            if base_price is None or stock_min is None or stock_max is None:
                errors.append({
                    "path": relative_path,
                    "line": line_number,
                    "kind": "value",
                    "fullType": full_type,
                    "message": "Invalid base price or stock value.",
                })
                continue
            if full_type in items:
                errors.append({
                    "path": relative_path,
                    "line": line_number,
                    "kind": "duplicate",
                    "fullType": full_type,
                    "message": "Item appeared in more than one runtime group.",
                })

            items[full_type] = {
                "fullType": full_type,
                "basePrice": base_price,
                "stock": {"min": max(0, stock_min), "max": max(0, stock_max)},
                "tags": list(group_tags),
                "origin": origin,
                "root": _header_value(headers, "root"),
                "category": _header_value(headers, "category"),
                "subcategory": _header_value(headers, "subcategory"),
                "leaf": _header_value(headers, "leaf"),
                "primaryPrefix": _header_value(headers, "primaryPrefix"),
                "path": relative_path,
                "line": line_number,
            }

    metadata = {
        "directory": str(root),
        "fileCount": len(files),
        "itemCount": len(items),
        "index": index_metadata,
        "parseErrors": errors,
        "parseErrorCount": len(errors),
    }
    return items, metadata
