"""Project Zomboid item-script field aliases and numeric properties."""

FIELD_ALIASES = {
    "displaycategory": "displayCategory", "itemtype": "itemType", "type": "type",
    "displayname": "displayName", "tooltip": "tooltip", "description": "description",
    "icon": "icon", "weight": "actualWeight", "actualweight": "actualWeight",
    "hungerchange": "hungerChange", "thirstchange": "thirstChange", "calories": "calories",
    "carbohydrates": "carbohydrates", "lipids": "lipids", "proteins": "proteins",
    "daysfresh": "daysFresh", "daystotallyrotten": "daysRotten", "foodtype": "foodType",
    "loottype": "lootType", "eattype": "eatType", "tags": "tags", "ammotype": "ammoType",
    "magazinetype": "magazineType", "parttype": "partType", "mounton": "mountOn",
    "canstack": "canStack", "bodylocation": "bodyLocation", "learnedrecipes": "learnedRecipes",
    "skilltrained": "skillTrained", "levelskilltrained": "levelSkillTrained",
    "lvlskilltrained": "levelSkillTrained", "maxleveltrained": "maxLevelTrained",
    "readtype": "readType", "worldstaticmodel": "worldStaticModel",
    "worldobjectsprite": "worldObjectSprite", "bloodclothingtype": "bloodClothingType",
    "opensound": "openSound", "closesound": "closeSound", "putinsound": "putInSound",
    "pourtype": "pourType", "doubleclickrecipe": "doubleClickRecipe",
    "replaceondeplete": "replaceOnDeplete", "replaceonuse": "replaceOnUse",
    "replaceoncooked": "replaceOnCooked", "oncooked": "onCooked",
    "evolvedrecipe": "evolvedRecipe", "evolvedrecipename": "evolvedRecipeName",
    "canbeequipped": "canBeEquipped", "acceptitemfunction": "acceptItemFunction",
    "isranged": "ranged", "ranged": "ranged", "isaimedfirearm": "aimedFirearm",
    "aimedfirearm": "aimedFirearm", "mindamage": "minDamage", "maxdamage": "maxDamage",
    "maxrange": "maxRange", "maxhitcount": "maxHitCount", "conditionmax": "conditionMax",
    "hitchance": "hitChance", "aimingtime": "aimingTime", "usedelta": "useDelta",
    "capacity": "capacity", "weightreduction": "weightReduction", "bitedefense": "biteDefense",
    "scratchdefense": "scratchDefense", "bulletdefense": "bulletDefense", "insulation": "insulation",
    "windresist": "windResistance", "windresistance": "windResistance",
    "twowhandweapon": "twoHandWeapon", "istwohandweapon": "twoHandWeapon", "spice": "spice",
    "poison": "poison", "alcoholpower": "alcoholPower", "fatiguechange": "fatigueChange",
    "reduceinfectionpower": "reduceInfectionPower", "bandagepower": "bandagePower",
    "mechanictype": "mechanicType", "canage": "canAge", "canbewrite": "canBeWrite",
    "canteat": "cantEat", "iscookable": "cookable", "isdrainable": "drainable",
    "canstorewater": "canStoreWater", "iscannedfood": "cannedFood", "iscanned": "cannedFood",
    "ispackaged": "packaged", "isfishinglure": "fishingLure",
    "isdangerousuncooked": "dangerousUncooked", "isgoodhot": "goodHot",
    "modid": "modId", "modname": "modName",
}

NUMBER_FIELDS = {
    "actualWeight", "hungerChange", "thirstChange", "calories", "carbohydrates", "lipids",
    "proteins", "daysFresh", "daysRotten", "levelSkillTrained", "maxLevelTrained", "minDamage",
    "maxDamage", "maxRange", "maxHitCount", "conditionMax", "hitChance", "aimingTime", "useDelta",
    "capacity", "weightReduction", "biteDefense", "scratchDefense", "bulletDefense", "insulation",
    "windResistance", "alcoholPower", "fatigueChange", "reduceInfectionPower", "bandagePower",
    "mechanicType",
}
