-- Typed market modifiers.  These values are deliberately separate from the
-- heuristic anchors: an anchor describes usefulness, while a modifier describes
-- a meaningful market distinction such as rarity, quality, or a registered
-- special item.
return {
    version = 1,
    tagModifiers = {
        ["Rarity.Common"] = { add = 11, reason = "Common rarity baseline" },
        ["Rarity.Uncommon"] = { add = 14, reason = "Uncommon rarity premium" },
        ["Rarity.Rare"] = { add = 17, reason = "Rare rarity premium" },
        ["Rarity.Legendary"] = { add = 20, reason = "Legendary rarity premium" },
        ["Rarity.UltraRare"] = { add = 27, reason = "Ultra-rare rarity premium" },
        ["Quality.Waste"] = { add = -10, reason = "Waste quality discount" },
        ["Quality.Luxury"] = { add = 40, reason = "Luxury quality premium" },
        ["Quality.Sterile"] = { add = 14, reason = "Sterile quality premium" },
        ["Theme.Combat"] = { add = 17, reason = "Combat theme premium" },
        ["Theme.Industrial"] = { add = 15, reason = "Industrial theme premium" },
        ["Theme.Militia"] = { add = 20, reason = "Militia theme premium" },
        ["Theme.Police"] = { add = 13, reason = "Police theme premium" },
        ["Theme.Primitive"] = { add = 7, reason = "Primitive theme premium" },
        ["Theme.Survival"] = { add = 20, reason = "Survival theme premium" },
        ["Theme.Winter"] = { add = 0, reason = "Winter seasonal descriptor" },
        -- Seasonal descriptors are neutral by default. Events can change
        -- these sandbox-editable values without changing classification.
        ["Theme.Summer"] = { add = 0, reason = "Summer seasonal descriptor" },
        ["Theme.Rain"] = { add = 0, reason = "Rain seasonal descriptor" },
        ["Theme.Swimwear"] = { add = 0, reason = "Swimwear seasonal descriptor" },
        ["Theme.GrowingSeason"] = { add = 0, reason = "Growing-season descriptor" },
        ["Theme.HuntingSeason"] = { add = 0, reason = "Hunting-season descriptor" },
        ["Theme.FishingSeason"] = { add = 0, reason = "Fishing-season descriptor" },
        ["Theme.Holiday"] = { add = 0, reason = "Holiday seasonal descriptor" },
        ["Theme.Camouflage"] = { add = 3, reason = "Camouflage pattern premium" },
        ["Theme.Canvas"] = { add = 3, reason = "Canvas material premium" },
        ["Theme.Cotton"] = { add = 1, reason = "Cotton material adjustment" },
        ["Theme.Denim"] = { add = 4, reason = "Denim material premium" },
        ["Theme.Fur"] = { add = 9, reason = "Fur material premium" },
        ["Theme.Leather"] = { add = 8, reason = "Leather material premium" },
        ["Theme.Rubber"] = { add = 3, reason = "Rubber material adjustment" },
        ["Theme.Silk"] = { add = 10, reason = "Silk material premium" },
        ["Theme.Thermal"] = { add = 4, reason = "Thermal protection premium" },
        ["Theme.Wool"] = { add = 5, reason = "Wool material premium" },
        ["Theme.HighCalorie"] = { add = 2, reason = "High-calorie food utility" },
        ["Theme.HighFat"] = { add = 1, reason = "High-fat food energy utility" },
        ["Theme.HighProtein"] = { add = 3, reason = "High-protein food utility" },
        ["Theme.HighCarbohydrate"] = { add = 1, reason = "High-carbohydrate food utility" },
        ["Theme.Hydrating"] = { add = 3, reason = "Hydrating food and beverage utility" },
        ["Theme.ThirstInducing"] = { add = -3, reason = "Thirst-inducing food penalty" },
        ["Theme.Communication"] = { add = 2, reason = "Two-way communication utility" },
    },
    categoryModifiers = {},
    itemModifiers = {},
}
