-- Market Sense Tag Taxonomy
-- Flat token taxonomy. Rewritten by refactor to use CamelCase flat tokens.

return {
    generatorVersion = 2,
    schemaVersion = 4,
    signatureVersion = "market-sense-v21-food-pricing-v2",
    pricingHeuristicVersion = 9,
    categoryOrder = {
        ["Food"]        = 1,
        ["Liquid"]      = 2,
        ["Weapon"]      = 3,
        ["Resource"]    = 4,
        ["Tool"]        = 5,
        ["Container"]   = 6,
        ["Clothing"]    = 7,
        ["Medical"]     = 8,
        ["Electronics"] = 9,
        ["Literature"]  = 10,
        ["Building"]    = 11,
        ["Misc"]        = 12,
    },
    -- Descriptor roots: these prefix dot-notation overlay tags
    descriptorRoots = {
        "Origin",
        "Quality",
        "Rarity",
        "Theme",
    },
    priceTags = {
        -- Root categories
        "Ammo","AmmoBox","AmmoCarton","AmmoMag",
        "Accessory","AccessoryArms","AccessoryFace","AccessoryHead","AccessoryHands","AccessoryJewelry","AccessoryLegs","AccessoryNeck","AccessoryTop",
        "Beverage","BeverageAlcohol","BeverageBeer","BeverageBox","BeverageCoffee","BeverageCocktail","BeverageDairy","BeverageEnergyDrink","BeverageJuice","BeverageMilk","BeverageSoda","BeverageSoftDrink","BeverageTea","BeverageWater","BeverageWine",
        "Liquid","LiquidBeverage","LiquidWater","LiquidTaintedWater","LiquidCarbonatedWater","LiquidSoda","LiquidJuice","LiquidSyrup","LiquidMilk","LiquidCoffee","LiquidTea","LiquidAlcohol","LiquidBeer","LiquidWine","LiquidBlood","LiquidAnimalBlood","LiquidAnimalGrease","LiquidFuel","LiquidDye","LiquidHairDye","LiquidChemical","LiquidMedical","LiquidIndustrial","LiquidUnknown",
        "BrokenWeapon",
        "Building","BuildingFixture","BuildingFixtureAppliance","BuildingFixtureLighting","BuildingFixturePlumbing","BuildingFurniture","BuildingFurnitureBed","BuildingFurnitureChair","BuildingFurnitureCounter","BuildingFurnitureDecor","BuildingFurnitureStorage","BuildingFurnitureTable","BuildingFurnitureLaundry","BuildingGarden","BuildingMoveable","BuildingSurvival","BuildingSurvivalSleepingBag","BuildingSurvivalTent","BuildingSurvivalTrap","BuildingVehicle",
        "BuildingRecreation","BuildingRecreationFitness","BuildingRecreationDrum","BuildingMedical","BuildingMedicalGurney","BuildingMedicalBloodbag","BuildingCrafting","BuildingCraftingForge","BuildingCraftingMasonry","BuildingLogistics","BuildingLogisticsPallet","BuildingInfrastructure","BuildingInfrastructureTraffic","BuildingFuneral","BuildingFuneralCoffin","BuildingAgriculture","BuildingAgricultureHay","BuildingAgricultureLivestock","BuildingAgricultureScarecrow","BuildingGardenDecor","BuildingDisplay","BuildingDisplaySkeleton","BuildingWallDecor","BuildingWallDecorMap","BuildingWallDecorCertificate","BuildingWallDecorNoticeboard",
        "ClothingBottom","ClothingFootwear","ClothingFullBody","ClothingHands","ClothingHead","ClothingOuterwear","ClothingSocks","ClothingTop","ClothingUnderwear",
        "Container","ContainerBag","ContainerBagBackpack","ContainerBagBandolier","ContainerBagDuffel","ContainerBagFanny","ContainerBagSatchel","ContainerAmmo","ContainerBox","ContainerLiquid","ContainerWearable","ContainerWearableAmmo",
        "Cooking","CookingCup","CookingCutlery","CookingOrTool","CookingPan","CookingUtensil",
        "ElectronicsBattery","ElectronicsCommunicator","ElectronicsFlashlight","ElectronicsGenerator","ElectronicsLight","ElectronicsRadio","ElectronicsTelevision","ElectronicsTransmitter","ElectronicsAppliance","ElectronicsLaundry","ElectronicsClock",
        "Electronics",
        "Explosive",
        "FirearmHandgun","FirearmRifle","FirearmShotgun",
        "Firearm",
        "FirstAid","Bandage",
        "FoodBaking","FoodCandy","FoodCheese","FoodCoffee","FoodDish","FoodEgg","FoodFruits","FoodHerb","FoodHotPepper","FoodInsect","FoodLivestock","FoodMeat","FoodMushroom","FoodNoExplicit","FoodNut","FoodPetFood","FoodPortion","FoodSeafood","FoodSeed","FoodSnack","FoodStaple","FoodStock","FoodSugar","FoodTea","FoodVegetables",
        "FoodNonPerishable","FoodNonPerishableBaking","FoodNonPerishableBoxed","FoodNonPerishableBread","FoodNonPerishableCandy","FoodNonPerishableCanned","FoodNonPerishableCheese","FoodNonPerishableDairy","FoodNonPerishableDish","FoodNonPerishableFruits","FoodNonPerishableMeat","FoodNonPerishablePortion","FoodNonPerishableSeafood","FoodNonPerishableSnack","FoodNonPerishableVegetables",
        "FoodPerishable","FoodPerishableBaking","FoodPerishableBread","FoodPerishableCandy","FoodPerishableCheese","FoodPerishableDairy","FoodPerishableDish","FoodPerishableFruits","FoodPerishableMeal","FoodPerishableMeat","FoodPerishablePortion","FoodPerishableSeafood","FoodPerishableSnack","FoodPerishableVegetables",
        "FoodOrFirstAid","FoodPreserved","FoodPreservedPickled","FoodSpice",
        "Food",
        "Gardening","GardeningCompostable","GardeningCompost","GardeningFertilizer","GardeningPestControl","GardeningSeed","GardeningSeedPacket",
        "KeyRing",
        "LiteratureAdult","LiteratureBrochure","LiteratureComic","LiteratureConsumable","LiteratureFancyBook","LiteratureFlier","LiteratureHardcover","LiteratureMagazine","LiteratureNewspaper","LiteratureOrJunk","LiteraturePhoto","LiteraturePictureBook","LiteratureRecipe","LiteratureRpgManual","LiteratureSoftcover",
        "Literature","SkillBook",
        "Material","MaterialBundled","MaterialButchering","MaterialCarpentry","MaterialChemical","MaterialConstruction","MaterialFireSource","MaterialGlass","MaterialHardware","MaterialMaintenance","MaterialMetalworking","MaterialOrJunk","MaterialPaper","MaterialPottery","MaterialStone","MaterialTailoring","MaterialWood",
        "Medical",
        "Memento","MementoPlushie","MementoOrContainer",
        "Misc","Junk",
        "ProtectiveGear",
        "Resource","ResourceFabric","ResourceFuel","ResourceHardware","ResourceMaterial","ResourceMetal","ResourceParts",
        "Smoking",
        "Tool","ToolBlacksmith","ToolButchering","ToolCarpentry","ToolCraft","ToolFarming","ToolFlintKnapping","ToolGardening","ToolMaintenance","ToolMasonry","ToolMechanics","ToolPottery","ToolTailoring","ToolWelding",
        "WeaponAxe","WeaponBlunt","WeaponCrafted","WeaponExplosive","WeaponImprovised","WeaponLongBlade","WeaponMelee","WeaponPart","WeaponRanged","WeaponSmallBlade","WeaponSmallBlunt","WeaponSpear","WeaponUnarmed",
        "Weapon",
        -- Descriptor overlay tags
        "Origin.Vanilla",
        "Quality.Luxury","Quality.Standard","Quality.Sterile","Quality.Waste",
        "Rarity.Common","Rarity.Legendary","Rarity.Rare","Rarity.Uncommon",
        "Theme.Combat","Theme.Industrial","Theme.Militia","Theme.Police","Theme.Primitive","Theme.Survival","Theme.Winter",
    },
}
